model:
  type: NEP
  elements:
  - Pb
  - Zr
  - Ti
  - O
  version: 4
potential:
  zbl:
    enabled: true
    cutoff: 1.5
    use_typewise_cutoff: 0.65
cutoff:
  radial: 8
  angular: 6
basis:
  n_max:
    radial: 8
    angular: 8
  basis_size:
    radial: 12
    angular: 12
  l_max:
  - 4
  - 2
  - 1
neural_network:
  neuron: 60
loss_weights:
  energy: 1.0
  forces: 1.0
  virial: 0.1
training:
  batch_size: 5000
  population_size: 50
  generations: 500000
